### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by TaoshanS** [zdimension/plexdlweb#3]
It would be a good idea to provide a docker image to avoid problems with dependencies and python version.

**Comment by zdimension** [comment]
Sorry for the time it took, I had a lot of projects to manage.

I published a Docker image, see 56859bb37325cbe273f7bcb496b0d986a7068908.

You can run like this:
```bash
docker run -d -p 8766:8766 \
  -e PDW_SERVER_URL=http://plex.johndoe.com:32400 \
  -e PDW_SERVER_ID=abcdef123456abcdef123456abcdef123456abcd \
  -e PDW_LANG=en \
  -v /thing/movies:/thing/movies \
  -v /thing/tvshows:/thing/tvshows \
  zdimension1/plexdlweb
```
