### ISSUE TITLE
not succesfully logging into plex

### ISSUE THREAD

**Issue by siddpen** [zdimension/plexdlweb#4]
I've dockeriezd this repo and have it running on my machine (the same machine hosts plex as well), but when I try to login with plex, I get this error: `No connection adapters were found for '192.168.68.66:32400/'`. That is the correct ip and port of plex

**Comment by zdimension** [comment]
> No connection adapters were found for

You need to include the protocol in the URL (e.g. `http://192.168.68.66:32400/`)

**Comment by siddpen** [comment]
🤕 knew it was simple! thanks for the great app!!
